#!/bin/bash

set -x




while true;do
# Fonksiyonları tanımlama ve çalıştırma
fonksiyon1() {
 array[0]="https://tls.tc/KllyY"     
array[1]="https://1hemsireninmutfagi.blogspot.com/"
array[2]="https://www.garippsikolog.com/"
'''
array[0]="https://www.garippsikolog.com/"
array[1]="https://www.garippsikolog.com/2023/03/ego-id-superego.html"
array[2]="https://www.garippsikolog.com/2022/12/zamansz-mektup.html"
array[3]="https://www.garippsikolog.com/2022/12/teknolojinin-gelismesinin.html"
array[4]="https://www.garippsikolog.com/2022/10/savas.html"
array[5]="https://www.garippsikolog.com/2022/10/toplum-yozlasmas.html"
array[6]="https://www.garippsikolog.com/2022/10/zaman.html"
array[7]="https://www.garippsikolog.com/2021/11/dusunme-yetisi.html"
array[8]="https://www.garippsikolog.com/2021/11/ritim.html"
array[9]="https://www.garippsikolog.com/2021/11/pratik-kadar-uygulamak-da-sart.html"
array[10]="https://www.garippsikolog.com/2021/11/kisiligini-tanimak.html"
array[11]="https://www.garippsikolog.com/2021/11/kullanilan-insanlar.html"
array[12]="https://www.garippsikolog.com/2021/11/sorumlular.html"
array[13]="https://www.garippsikolog.com/2021/11/zamani-gecen-seyler.html"
array[14]="https://www.garippsikolog.com/2021/11/kirik-bir-ayna.html"
array[15]="https://www.garippsikolog.com/2021/11/umut.html"
array[16]="https://www.garippsikolog.com/2021/11/bir-uyanisa-gecmek.html"
array[17]="https://www.garippsikolog.com/2021/11/evlilik.html"
array[18]="https://www.garippsikolog.com/2021/11/adalet-kader-iliskisi.html"
array[19]="https://www.garippsikolog.com/2021/11/hicbir-sey.html"
array[20]="https://www.garippsikolog.com/2021/11/kaderi-bilememek-mi.html"
array[21]="https://www.garippsikolog.com/2021/11/kader.html"
array[22]="https://www.garippsikolog.com/2021/11/hayaller.html"
array[23]="https://www.garippsikolog.com/2021/11/insan-insan.html"
array[24]="https://www.garippsikolog.com/2021/07/twins-global-app-developer.html"
array[25]="https://www.garippsikolog.com/2021/01/hu-hu-hu-hu-medet-ya-ali.html"
array[26]="https://www.garippsikolog.com/2021/01/telegram-ozellikleri-nerelrdir.html"
array[27]="https://www.garippsikolog.com/2021/01/telegramda-kisileri-esitle-ne-demek.html"
array[28]="https://www.garippsikolog.com/2021/01/tanr-var-mdr.html"
array[29]="https://www.garippsikolog.com/2021/01/sahi-gercek-yorgunluk-neydi.html"
array[30]="https://www.garippsikolog.com/2021/01/karamsar-hayat-benimsemeyin.html"
array[31]="https://www.garippsikolog.com/2021/01/b-azen-sonsuz-ogrenme-frsat-size.html"
array[32]="https://www.garippsikolog.com/2020/09/gunahlar-var-m-ozunde.html"
array[33]="https://www.garippsikolog.com/2020/08/her-saniyede-elimden-gelen-her-seyi.html"
array[34]="https://www.garippsikolog.com/2020/08/bir-cumleyi-her-zaman-bir-edatla-bitirin.html"
array[35]="https://www.garippsikolog.com/2020/08/bir-seyi-yapmak-basittir-onu.html"
array[36]="https://www.garippsikolog.com/2020/08/ayletme-beni.html"
array[37]="https://www.garippsikolog.com/2020/08/yarab-bu-ne-derttir.html"
array[38]="https://www.garippsikolog.com/2020/08/havada-bulut-yok-notalar.html"
array[39]="https://www.garippsikolog.com/2020/05/secilmis-sozcukler_15.html"
array[40]="https://www.garippsikolog.com/2020/05/theodor-herzl-kimdir.html"
array[41]="https://www.garippsikolog.com/2020/03/c-in-ile-abd-arasnda-uzun-suredir.html"
array[42]="https://www.garippsikolog.com/2020/01/lum-hak-edilir-mi-yoksa-hak-edilmeye.html"
array[43]="https://www.garippsikolog.com/2020/02/simpleserver-exe-ve-config-ayar-dosyas.html"
array[44]="https://www.garippsikolog.com/2020/01/hayallerim.html"
array[45]="https://www.garippsikolog.com/2020/01/politik-dusunme-yeteneginiz-var-mi.html"
array[46]="https://www.garippsikolog.com/2020/01/derinde-bir-yerde.html"
array[47]="https://www.garippsikolog.com/2020/01/bedenlerimiz-buyudukce-insanlgmz.html"
array[48]="https://www.garippsikolog.com/2020/01/silueti-insan-olup-ozunde-insan.html"
array[49]="https://www.garippsikolog.com/2020/01/gosterdiginiz-davranslar-bazen-hayatnza.html"
array[50]="https://www.garippsikolog.com/2020/01/dusunmeyi-dusunme-olaslg.html"
array[51]="https://www.garippsikolog.com/2020/01/beden-yorulursa.html"
array[52]="https://www.garippsikolog.com/2020/01/arkadaslg-gozden-gecirmek.html"
array[53]="https://www.garippsikolog.com/2020/01/benligini-korumak.html"
array[54]="https://www.garippsikolog.com/2020/01/umitsizlige-baks.html"
array[55]="https://www.garippsikolog.com/2020/01/dostluk-paradigmas.html"
array[56]="https://www.garippsikolog.com/2020/01/brsk_4.html"
array[57]="https://www.garippsikolog.com/2020/01/cok-sevmek-zararli-mi.html"
array[58]="https://www.garippsikolog.com/2020/01/hayatnz-sorgulayn.html"
array[59]="https://www.garippsikolog.com/2020/01/brsk.html"
array[60]="https://www.garippsi30kolog.com/2020/01/yurek-sznts.html"
array[61]="https://www.garippsikolog.com/2020/01/kader-olgusuna-inanmak-m-yoksa-yanlgsna.html"
array[62]="https://www.garippsikolog.com/2020/01/hayatiniza-mudahale.html"
array[63]="https://www.garippsikolog.com/2020/01/zihin-uyank-vucut-uyuyor.html"
array[64]="https://www.garippsikolog.com/2020/01/blog-post.html"
array[65]="https://www.garippsikolog.com/2020/01/hakknda.html"
array[66]="https://www.garippsikolog.com/search/label/garippsikolog"
array[67]="https://www.garippsikolog.com/search/label/b.r.s.k"
array[68]="https://www.garippsikolog.com/search/label/bayramhoca"
array[69]="https://www.garippsikolog.com/search/label/anonim-sair"
array[70]="https://www.garippsikolog.com/search/label/%C5%9Fiir"
array[71]="https://www.garippsikolog.com/search/label/nota"
array[72]="https://www.garippsikolog.com/search/label/s%C3%B6zc%C3%BCk"
array[73]="https://www.garippsikolog.com/2020/02/simpleserver-exe-ve-config-ayar-dosyas.html"
array[74]="https://www.garippsikolog.com/search/label/pc"
array[75]="https://www.garippsikolog.com/2020/01/blog-post.html"
           '''
size=${#array[@]}
index=$(($RANDOM % $size))
i=${array[$index]}


    google-chrome --new-window --incognito --user-data-dir=/tmp/ntv-profile $i&
    pid_1=$!
    echo "Fonksiyon 1 PID: $pid_1"
    sleep 60
    kill $pid_1
    echo "Fonksiyon 1 sonlandırıldı."
}

fonksiyon2() {
 array[0]="https://tls.tc/KllyY"     
array[1]="https://1hemsireninmutfagi.blogspot.com/"
array[2]="https://www.garippsikolog.com/"
'''
array[0]="https://www.garippsikolog.com/"
array[1]="https://www.garippsikolog.com/2023/03/ego-id-superego.html"
array[2]="https://www.garippsikolog.com/2022/12/zamansz-mektup.html"
array[3]="https://www.garippsikolog.com/2022/12/teknolojinin-gelismesinin.html"
array[4]="https://www.garippsikolog.com/2022/10/savas.html"
array[5]="https://www.garippsikolog.com/2022/10/toplum-yozlasmas.html"
array[6]="https://www.garippsikolog.com/2022/10/zaman.html"
array[7]="https://www.garippsikolog.com/2021/11/dusunme-yetisi.html"
array[8]="https://www.garippsikolog.com/2021/11/ritim.html"
array[9]="https://www.garippsikolog.com/2021/11/pratik-kadar-uygulamak-da-sart.html"
array[10]="https://www.garippsikolog.com/2021/11/kisiligini-tanimak.html"
array[11]="https://www.garippsikolog.com/2021/11/kullanilan-insanlar.html"
array[12]="https://www.garippsikolog.com/2021/11/sorumlular.html"
array[13]="https://www.garippsikolog.com/2021/11/zamani-gecen-seyler.html"
array[14]="https://www.garippsikolog.com/2021/11/kirik-bir-ayna.html"
array[15]="https://www.garippsikolog.com/2021/11/umut.html"
array[16]="https://www.garippsikolog.com/2021/11/bir-uyanisa-gecmek.html"
array[17]="https://www.garippsikolog.com/2021/11/evlilik.html"
array[18]="https://www.garippsikolog.com/2021/11/adalet-kader-iliskisi.html"
array[19]="https://www.garippsikolog.com/2021/11/hicbir-sey.html"
array[20]="https://www.garippsikolog.com/2021/11/kaderi-bilememek-mi.html"
array[21]="https://www.garippsikolog.com/2021/11/kader.html"
array[22]="https://www.garippsikolog.com/2021/11/hayaller.html"
array[23]="https://www.garippsikolog.com/2021/11/insan-insan.html"
array[24]="https://www.garippsikolog.com/2021/07/twins-global-app-developer.html"
array[25]="https://www.garippsikolog.com/2021/01/hu-hu-hu-hu-medet-ya-ali.html"
array[26]="https://www.garippsikolog.com/2021/01/telegram-ozellikleri-nerelrdir.html"
array[27]="https://www.garippsikolog.com/2021/01/telegramda-kisileri-esitle-ne-demek.html"
array[28]="https://www.garippsikolog.com/2021/01/tanr-var-mdr.html"
array[29]="https://www.garippsikolog.com/2021/01/sahi-gercek-yorgunluk-neydi.html"
array[30]="https://www.garippsikolog.com/2021/01/karamsar-hayat-benimsemeyin.html"
array[31]="https://www.garippsikolog.com/2021/01/b-azen-sonsuz-ogrenme-frsat-size.html"
array[32]="https://www.garippsikolog.com/2020/09/gunahlar-var-m-ozunde.html"
array[33]="https://www.garippsikolog.com/2020/08/her-saniyede-elimden-gelen-her-seyi.html"
array[34]="https://www.garippsikolog.com/2020/08/bir-cumleyi-her-zaman-bir-edatla-bitirin.html"
array[35]="https://www.garippsikolog.com/2020/08/bir-seyi-yapmak-basittir-onu.html"
array[36]="https://www.garippsikolog.com/2020/08/ayletme-beni.html"
array[37]="https://www.garippsikolog.com/2020/08/yarab-bu-ne-derttir.html"
array[38]="https://www.garippsikolog.com/2020/08/havada-bulut-yok-notalar.html"
array[39]="https://www.garippsikolog.com/2020/05/secilmis-sozcukler_15.html"
array[40]="https://www.garippsikolog.com/2020/05/theodor-herzl-kimdir.html"
array[41]="https://www.garippsikolog.com/2020/03/c-in-ile-abd-arasnda-uzun-suredir.html"
array[42]="https://www.garippsikolog.com/2020/01/lum-hak-edilir-mi-yoksa-hak-edilmeye.html"
array[43]="https://www.garippsikolog.com/2020/02/simpleserver-exe-ve-config-ayar-dosyas.html"
array[44]="https://www.garippsikolog.com/2020/01/hayallerim.html"
array[45]="https://www.garippsikolog.com/2020/01/politik-dusunme-yeteneginiz-var-mi.html"
array[46]="https://www.garippsikolog.com/2020/01/derinde-bir-yerde.html"
array[47]="https://www.garippsikolog.com/2020/01/bedenlerimiz-buyudukce-insanlgmz.html"
array[48]="https://www.garippsikolog.com/2020/01/silueti-insan-olup-ozunde-insan.html"
array[49]="https://www.garippsikolog.com/2020/01/gosterdiginiz-davranslar-bazen-hayatnza.html"
array[50]="https://www.garippsikolog.com/2020/01/dusunmeyi-dusunme-olaslg.html"
array[51]="https://www.garippsikolog.com/2020/01/beden-yorulursa.html"
array[52]="https://www.garippsikolog.com/2020/01/arkadaslg-gozden-gecirmek.html"
array[53]="https://www.garippsikolog.com/2020/01/benligini-korumak.html"
array[54]="https://www.garippsikolog.com/2020/01/umitsizlige-baks.html"
array[55]="https://www.garippsikolog.com/2020/01/dostluk-paradigmas.html"
array[56]="https://www.garippsikolog.com/2020/01/brsk_4.html"
array[57]="https://www.garippsikolog.com/2020/01/cok-sevmek-zararli-mi.html"
array[58]="https://www.garippsikolog.com/2020/01/hayatnz-sorgulayn.html"
array[59]="https://www.garippsikolog.com/2020/01/brsk.html"
array[60]="https://www.garippsikolog.com/2020/01/yurek-sznts.html"
array[61]="https://www.garippsikolog.com/2020/01/kader-olgusuna-inanmak-m-yoksa-yanlgsna.html"
array[62]="https://www.garippsikolog.com/2020/01/hayatiniza-mudahale.html"
array[63]="https://www.garippsikolog.com/2020/01/zihin-uyank-vucut-uyuyor.html"
array[64]="https://www.garippsikolog.com/2020/01/blog-post.html"
array[65]="https://www.garippsikolog.com/2020/01/hakknda.html"
array[66]="https://www.garippsikolog.com/search/label/garippsikolog"
array[67]="https://www.garippsikolog.com/search/label/b.r.s.k"
array[68]="https://www.garippsikolog.com/search/label/bayramhoca"
array[69]="https://www.garippsikolog.com/search/label/anonim-sair"
array[70]="https://www.garippsikolog.com/search/label/%C5%9Fiir"
array[71]="https://www.garippsikolog.com/search/label/nota"
array[72]="https://www.garippsikolog.com/search/label/s%C3%B6zc%C3%BCk"
array[73]="https://www.garippsikolog.com/2020/02/simpleserver-exe-ve-config-ayar-dosyas.html"
array[74]="https://www.garippsikolog.com/search/label/pc"
array[75]="https://www.garippsikolog.com/2020/01/blog-post.html"
    '''       
size=${#array[@]}
index=$(($RANDOM % $size))
i=${array[$index]}
    google-chrome --new-window --incognito --user-data-dir=/tmp/tgrthaber-profile $i&
    pid_2=$!
    echo "Fonksiyon 2 PID: $pid_2"
    sleep 35
    kill $pid_2
    echo "Fonksiyon 2 sonlandırıldı."
}

fonksiyon3() {
 array[0]="https://tls.tc/KllyY"     
array[1]="https://1hemsireninmutfagi.blogspot.com/"
array[2]="https://www.garippsikolog.com/"
'''
array[0]="https://www.garippsikolog.com/"
array[1]="https://www.garippsikolog.com/2023/03/ego-id-superego.html"
array[2]="https://www.garippsikolog.com/2022/12/zamansz-mektup.html"
array[3]="https://www.garippsikolog.com/2022/12/teknolojinin-gelismesinin.html"
array[4]="https://www.garippsikolog.com/2022/10/savas.html"
array[5]="https://www.garippsikolog.com/2022/10/toplum-yozlasmas.html"
array[6]="https://www.garippsikolog.com/2022/10/zaman.html"
array[7]="https://www.garippsikolog.com/2021/11/dusunme-yetisi.html"
array[8]="https://www.garippsikolog.com/2021/11/ritim.html"
array[9]="https://www.garippsikolog.com/2021/11/pratik-kadar-uygulamak-da-sart.html"
array[10]="https://www.garippsikolog.com/2021/11/kisiligini-tanimak.html"
array[11]="https://www.garippsikolog.com/2021/11/kullanilan-insanlar.html"
array[12]="https://www.garippsikolog.com/2021/11/sorumlular.html"
array[13]="https://www.garippsikolog.com/2021/11/zamani-gecen-seyler.html"
array[14]="https://www.garippsikolog.com/2021/11/kirik-bir-ayna.html"
array[15]="https://www.garippsikolog.com/2021/11/umut.html"
array[16]="https://www.garippsikolog.com/2021/11/bir-uyanisa-gecmek.html"
array[17]="https://www.garippsikolog.com/2021/11/evlilik.html"
array[18]="https://www.garippsikolog.com/2021/11/adalet-kader-iliskisi.html"
array[19]="https://www.garippsikolog.com/2021/11/hicbir-sey.html"
array[20]="https://www.garippsikolog.com/2021/11/kaderi-bilememek-mi.html"
array[21]="https://www.garippsikolog.com/2021/11/kader.html"
array[22]="https://www.garippsikolog.com/2021/11/hayaller.html"
array[23]="https://www.garippsikolog.com/2021/11/insan-insan.html"
array[24]="https://www.garippsikolog.com/2021/07/twins-global-app-developer.html"
array[25]="https://www.garippsikolog.com/2021/01/hu-hu-hu-hu-medet-ya-ali.html"
array[26]="https://www.garippsikolog.com/2021/01/telegram-ozellikleri-nerelrdir.html"
array[27]="https://www.garippsikolog.com/2021/01/telegramda-kisileri-esitle-ne-demek.html"
array[28]="https://www.garippsikolog.com/2021/01/tanr-var-mdr.html"
array[29]="https://www.garippsikolog.com/2021/01/sahi-gercek-yorgunluk-neydi.html"
array[30]="https://www.garippsikolog.com/2021/01/karamsar-hayat-benimsemeyin.html"
array[31]="https://www.garippsikolog.com/2021/01/b-azen-sonsuz-ogrenme-frsat-size.html"
array[32]="https://www.garippsikolog.com/2020/09/gunahlar-var-m-ozunde.html"
array[33]="https://www.garippsikolog.com/2020/08/her-saniyede-elimden-gelen-her-seyi.html"
array[34]="https://www.garippsikolog.com/2020/08/bir-cumleyi-her-zaman-bir-edatla-bitirin.html"
array[35]="https://www.garippsikolog.com/2020/08/bir-seyi-yapmak-basittir-onu.html"
array[36]="https://www.garippsikolog.com/2020/08/ayletme-beni.html"
array[37]="https://www.garippsikolog.com/2020/08/yarab-bu-ne-derttir.html"
array[38]="https://www.garippsikolog.com/2020/08/havada-bulut-yok-notalar.html"
array[39]="https://www.garippsikolog.com/2020/05/secilmis-sozcukler_15.html"
array[40]="https://www.garippsikolog.com/2020/05/theodor-herzl-kimdir.html"
array[41]="https://www.garippsikolog.com/2020/03/c-in-ile-abd-arasnda-uzun-suredir.html"
array[42]="https://www.garippsikolog.com/2020/01/lum-hak-edilir-mi-yoksa-hak-edilmeye.html"
array[43]="https://www.garippsikolog.com/2020/02/simpleserver-exe-ve-config-ayar-dosyas.html"
array[44]="https://www.garippsikolog.com/2020/01/hayallerim.html"
array[45]="https://www.garippsikolog.com/2020/01/politik-dusunme-yeteneginiz-var-mi.html"
array[46]="https://www.garippsikolog.com/2020/01/derinde-bir-yerde.html"
array[47]="https://www.garippsikolog.com/2020/01/bedenlerimiz-buyudukce-insanlgmz.html"
array[48]="https://www.garippsikolog.com/2020/01/silueti-insan-olup-ozunde-insan.html"
array[49]="https://www.garippsikolog.com/2020/01/gosterdiginiz-davranslar-bazen-hayatnza.html"
array[50]="https://www.garippsikolog.com/2020/01/dusunmeyi-dusunme-olaslg.html"
array[51]="https://www.garippsikolog.com/2020/01/beden-yorulursa.html"
array[52]="https://www.garippsikolog.com/2020/01/arkadaslg-gozden-gecirmek.html"
array[53]="https://www.garippsikolog.com/2020/01/benligini-korumak.html"
array[54]="https://www.garippsikolog.com/2020/01/umitsizlige-baks.html"
array[55]="https://www.garippsikolog.com/2020/01/dostluk-paradigmas.html"
array[56]="https://www.garippsikolog.com/2020/01/brsk_4.html"
array[57]="https://www.garippsikolog.com/2020/01/cok-sevmek-zararli-mi.html"
array[58]="https://www.garippsikolog.com/2020/01/hayatnz-sorgulayn.html"
array[59]="https://www.garippsikolog.com/2020/01/brsk.html"
array[60]="https://www.garippsikolog.com/2020/01/yurek-sznts.html"
array[61]="https://www.garippsikolog.com/2020/01/kader-olgusuna-inanmak-m-yoksa-yanlgsna.html"
array[62]="https://www.garippsikolog.com/2020/01/hayatiniza-mudahale.html"
array[63]="https://www.garippsikolog.com/2020/01/zihin-uyank-vucut-uyuyor.html"
array[64]="https://www.garippsikolog.com/2020/01/blog-post.html"
array[65]="https://www.garippsikolog.com/2020/01/hakknda.html"
array[66]="https://www.garippsikolog.com/search/label/garippsikolog"
array[67]="https://www.garippsikolog.com/search/label/b.r.s.k"
array[68]="https://www.garippsikolog.com/search/label/bayramhoca"
array[69]="https://www.garippsikolog.com/search/label/anonim-sair"
array[70]="https://www.garippsikolog.com/search/label/%C5%9Fiir"
array[71]="https://www.garippsikolog.com/search/label/nota"
array[72]="https://www.garippsikolog.com/search/label/s%C3%B6zc%C3%BCk"
array[73]="https://www.garippsikolog.com/2020/02/simpleserver-exe-ve-config-ayar-dosyas.html"
array[74]="https://www.garippsikolog.com/search/label/pc"
array[75]="https://www.garippsikolog.com/2020/01/blog-post.html"
           '''
size=${#array[@]}
index=$(($RANDOM % $size))
i=${array[$index]}

    google-chrome --new-window --incognito --user-data-dir=/tmp/haberturk-profile $i&
    pid_3=$!
    echo "Fonksiyon 3 PID: $pid_3"
    sleep 45
    kill $pid_3
    echo "Fonksiyon 3 sonlandırıldı."
}

# Fonksiyonları arka planda çalıştırma
fonksiyon1&
sleep 5
fonksiyon2&
sleep 10
fonksiyon3&
sleep 3
done
